version: '3'

services:
    app:
        build: .
        environment:
            REDIS_URL: redis://redis:6379
            CLICKHOUSE_HOST: $CLICKHOUSE_HOST
            CLICKHOUSE_DATABASE: zetta
            CLICKHOUSE_USER: zepeto-data
            CLICKHOUSE_PASSWORD: zetta1234
            CLICKHOUSE_CLUSTER: zetta_cluster
            CLICKHOUSE_SECURE: false
            CLICKHOUSE_VERIFY: false
            CLICKHOUSE_CA: $CLICKHOUSE_CA
        command:
            - bash
            - -c
            - |
                python manage.py migrate
                python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - '8000:8000'
    web:
        build: ./frontend
        ports:
            - "3000:3000"

    redis:
        image: redis:6.2.7-alpine
        restart: on-failure
        ports:
            - '6388:6379'
        command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb

    worker:
        build: .
        environment:
            REDIS_URL: redis://redis:6379
            CLICKHOUSE_HOST: $CLICKHOUSE_HOST
            CLICKHOUSE_DATABASE: zetta
            CLICKHOUSE_USER: zepeto-data
            CLICKHOUSE_PASSWORD: zetta1234
            CLICKHOUSE_CLUSTER: zetta_cluster
            CLICKHOUSE_SECURE: false
            CLICKHOUSE_VERIFY: false
            CLICKHOUSE_CA: $CLICKHOUSE_CA
        command:
            - ./bin/celery
        volumes:
           - .:/code